// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    BaseGameTable: typeof import('./src/components/BaseGameTable.vue')['default']
    BaseHand: typeof import('./src/components/BaseHand.vue')['default']
    BaseImg: typeof import('./src/components/BaseImg.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    BaseNavigation: typeof import('./src/components/BaseNavigation.vue')['default']
    BaseSettings: typeof import('./src/components/BaseSettings.vue')['default']
    BaseToggler: typeof import('./src/components/BaseToggler.vue')['default']
  }
}
